"""
Email Sender Module
Handles sending HTML-formatted job alert emails via Gmail SMTP.
"""

import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Dict, Optional
from datetime import datetime
from jinja2 import Environment, FileSystemLoader, select_autoescape


class EmailSender:
    """
    Sends HTML-formatted emails via Gmail SMTP.
    
    Requires environment variables:
    - GMAIL_USER: Gmail address to send from
    - GMAIL_APP_PASSWORD: Gmail app password (NOT regular password)
    
    To generate an app password:
    1. Enable 2-Factor Authentication on your Google account
    2. Go to: https://myaccount.google.com/apppasswords
    3. Generate a new app password for "Mail"
    """
    
    SMTP_SERVER = "smtp.gmail.com"
    SMTP_PORT = 587  # TLS port
    
    def __init__(self, template_dir: str = "templates"):
        """
        Initialize the email sender.
        
        Args:
            template_dir: Directory containing email templates
        """
        self.gmail_user = os.environ.get('GMAIL_USER', '')
        self.gmail_password = os.environ.get('GMAIL_APP_PASSWORD', '')
        self.recipient_email = os.environ.get('RECIPIENT_EMAIL', 'aamirtinwala7@gmail.com')
        
        # Set up Jinja2 template environment
        self.template_env = Environment(
            loader=FileSystemLoader(template_dir),
            autoescape=select_autoescape(['html', 'xml'])
        )
    
    def _is_configured(self) -> bool:
        """Check if email credentials are configured."""
        return bool(self.gmail_user and self.gmail_password)
    
    def _render_email_body(self, jobs: List[Dict]) -> str:
        """
        Render the HTML email body using Jinja2 template.
        
        Args:
            jobs: List of job dictionaries to include in email
            
        Returns:
            Rendered HTML string
        """
        try:
            template = self.template_env.get_template('email_template.html')
            return template.render(
                jobs=jobs,
                job_count=len(jobs),
                date=datetime.now().strftime("%B %d, %Y")
            )
        except Exception as e:
            print(f"[Email] Template error: {e}")
            # Fallback to plain text format
            return self._render_fallback_body(jobs)
    
    def _render_fallback_body(self, jobs: List[Dict]) -> str:
        """Render a simple HTML fallback if template fails."""
        html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; padding: 20px;">
            <h1>🚀 {len(jobs)} New Job Opportunities Found!</h1>
            <p>Here are the latest developer positions matching your criteria:</p>
            <hr>
        """
        
        for job in jobs:
            html += f"""
            <div style="margin: 20px 0; padding: 15px; border: 1px solid #ddd; border-radius: 8px;">
                <h2 style="margin: 0 0 10px 0;">{job.get('title', 'Unknown Position')}</h2>
                <p><strong>Company:</strong> {job.get('company', 'Unknown')}</p>
                <p><strong>Location:</strong> {job.get('location', 'Not specified')}</p>
                <p><strong>Type:</strong> {job.get('job_type', 'Not specified')}</p>
                <p><strong>Compensation:</strong> {job.get('compensation', 'Not specified')}</p>
                <p><strong>Skills:</strong> {job.get('skills', 'Not specified')}</p>
                <p><strong>Posted:</strong> {job.get('posted_date', 'Not specified')}</p>
                <p><strong>Source:</strong> {job.get('source', 'Unknown')}</p>
                <p><a href="{job.get('url', '#')}" style="background: #667eea; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Apply Now</a></p>
            </div>
            """
        
        html += """
            <hr>
            <p style="color: #666; font-size: 12px;">
                This email was automatically generated by Job Search Automation Tool.
            </p>
        </body>
        </html>
        """
        
        return html
    
    def _create_message(self, to_email: str, subject: str, html_body: str) -> MIMEMultipart:
        """
        Create the email message object.
        
        Args:
            to_email: Recipient email address
            subject: Email subject line
            html_body: HTML content for the email body
            
        Returns:
            MIMEMultipart message object
        """
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = self.gmail_user
        msg['To'] = to_email
        
        # Create plain text version (basic fallback)
        text_content = "New job opportunities found. Please view this email in an HTML-capable client."
        
        # Attach both plain text and HTML versions
        part1 = MIMEText(text_content, 'plain')
        part2 = MIMEText(html_body, 'html')
        
        msg.attach(part1)
        msg.attach(part2)
        
        return msg
    
    def send_job_alert(self, jobs: List[Dict], recipient: str = None) -> bool:
        """
        Send a job alert email with the provided jobs.
        
        Args:
            jobs: List of job dictionaries to include in the email
            recipient: Override recipient email (optional)
            
        Returns:
            True if email sent successfully, False otherwise
        """
        if not jobs:
            print("[Email] No jobs to send. Skipping email.")
            return False
        
        if not self._is_configured():
            print("[Email] ERROR: Email credentials not configured!")
            print("[Email] Set GMAIL_USER and GMAIL_APP_PASSWORD environment variables.")
            return False
        
        recipient = recipient or self.recipient_email
        subject = "New Remote & Entry-Level Developer Opportunities"
        
        print(f"[Email] Preparing to send {len(jobs)} jobs to {recipient}")
        
        try:
            # Render email body
            html_body = self._render_email_body(jobs)
            
            # Create message
            msg = self._create_message(recipient, subject, html_body)
            
            # Connect to Gmail SMTP and send
            print(f"[Email] Connecting to {self.SMTP_SERVER}...")
            
            with smtplib.SMTP(self.SMTP_SERVER, self.SMTP_PORT) as server:
                server.starttls()  # Enable TLS encryption
                server.login(self.gmail_user, self.gmail_password)
                server.send_message(msg)
            
            print(f"[Email] ✓ Successfully sent email to {recipient}")
            return True
            
        except smtplib.SMTPAuthenticationError as e:
            print(f"[Email] Authentication failed: {e}")
            print("[Email] Make sure you're using an App Password, not your regular Gmail password.")
            return False
        except smtplib.SMTPException as e:
            print(f"[Email] SMTP error: {e}")
            return False
        except Exception as e:
            print(f"[Email] Error sending email: {e}")
            return False
    
    def send_test_email(self, recipient: str = None) -> bool:
        """Send a test email to verify configuration."""
        test_jobs = [
            {
                'title': 'Test Position - Junior Developer',
                'company': 'Test Company Inc.',
                'url': 'https://example.com/test-job',
                'location': 'Remote',
                'job_type': 'Entry-Level',
                'compensation': '$50,000 - $70,000/year',
                'skills': 'Python, JavaScript, React, SQL',
                'posted_date': datetime.now().strftime("%Y-%m-%d"),
                'source': 'Test Source'
            }
        ]
        
        print("[Email] Sending test email...")
        return self.send_job_alert(test_jobs, recipient)


if __name__ == "__main__":
    # Test the email sender (requires environment variables)
    sender = EmailSender()
    
    if sender._is_configured():
        success = sender.send_test_email()
        if success:
            print("\n✓ Test email sent successfully!")
        else:
            print("\n✗ Failed to send test email.")
    else:
        print("\nEmail credentials not configured.")
        print("Set these environment variables:")
        print("  - GMAIL_USER=your-email@gmail.com")
        print("  - GMAIL_APP_PASSWORD=your-16-char-app-password")
